# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: From Samples to Knowledge 2025
author: Sarah McArdle, Zbigniew Mikulski, Michael Nelson
copyright: 2025
# logo: logo.png

# Only build files in the table of contents.
only_build_toc_files: true


# Don't execute the code cells in the book when building it
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
# bibtex_bibfiles:
#  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/saramcardle/FS2K  # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: true

parse:
  myst_enable_extensions:
    - html_image